### PR TITLE
[Task  CS-89] Added cycles summary

### PR DESCRIPTION
**Pull request by skusnierz**

### CODE REVIEW

**Review by szebniok — APPROVED** [review]

**Review by twrdyyy — APPROVED** [review]

**Comment by twrdyyy** [comment]
Honestly, one of the greatest code I've seen so far ❤️  do not change @skusnierz and keep going above perfection

**Comment by skusnierz** [comment]
> Honestly, one of the greatest code I've seen so far  do not change @skusnierz and keep going above perfection

Well, thanks a lot, I do my best, my best backend friend @twrdyyy :heart:

**Comment by Qizot** [comment]
Wow, it is the first time I look up this repository and the code is an astonishing achievement! @twrdyyy is right, the best code I've seen for a long time! Is it possible that you could teach my child? I'm not skilled enough compared to you, your majesty!

**Comment by twrdyyy** [comment]
@skusnierz What's going on with checks? Is it related to travis/checks errors or some magical logic behind code? It is hard for me to understand your code complexity 😢

**Pull request merged**
